version: '3'
services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    volumes:
      - 'tsdemo_mysql_data:/var/lib/mysql'
      - 'tsdemo_mysqld:/var/run/mysqld'
    ports:
      - "33061:3306"
    logging:
      driver: none

  app:
    platform: linux/x86_64
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    expose:
      - '3000'
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: demo_development
      RAILS_ENV: development
      SPHINX_HOST: 127.0.0.0
    depends_on:
      - database
    volumes:
      - ".:/app"
      - 'tsdemo_mysqld:/var/run/mysqld'

volumes:
  tsdemo_mysql_data: {}
  tsdemo_mysqld: {}
  app: {}
