default: &default
  # address: <%= ENV.fetch('SPHINX_HOST') { 'database' } %>
  mysql41: 9312
  configuration_file: "/app/config/sphinx.conf"
  pid_file: "/app/log/searchd.development.pid"
  binlog_path: "/app/tmp/binlog/development"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
